name: Deploy
on:
  push:
    branches:
      - main
jobs:
  checkout_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ERNESTNS_DDB54 }}
          channelId: live
          projectId: ernestns-ddb54
